---
title: "K19"
author: "Michelle Boyce"
date: "02/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(splines)
library(Hmisc)
library(formattable)
```

```{r}
get_dataset <- function() {
  data_root <- "/Users/susy/workbench/K19/COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/"
  data_files <- Sys.glob(paste(data_root,"*.csv",sep=""))
  
  # reference list
  header_hist = list(
    '01-22-2020'=list('Province.State','Country.Region','Last.Update','Confirmed','Deaths','Recovered'),
    '03-01-2020'=list('Province.State','Country.Region','Last.Update','Confirmed','Deaths','Recovered','Latitude','Longitude'),
    '03-22-2020'=list('FIPS','Admin2','Province_State','Country_Region','Last_Update','Lat','Long_','Confirmed','Deaths','Recovered','Active','Combined_Key'),
    'time_stamp'=list('FIPS','Admin2','Province_State','Country_Region','Last_Update','Lat','Long_','Confirmed','Deaths','Recovered','Active','Combined_Key','Incident_Rate','Case_Fatality_Ratio')
  )
  
  # alt-names
  last.update = c('Last.Update','Last_Update')
  latitude = c('Latitude','Lat')
  longitude = c('Longitude','Long_')
  province.state = c('Province.State','Province_State')
  country.region = c('Country.Region','Province_State')

  df <- data.frame(
    date=character(),
    last_update=character(),
    lat=numeric(),
    long=numeric(),
    province_state=character(),
    country_region=character(),
    confirmed=numeric(),
    deaths=numeric(),
    recovered=numeric(),
    active=numeric(),
    stringsAsFactors = FALSE
  )
  for (data_file in data_files) {
    time_stamp <- sub(".csv","",sub(data_root,"",data_file))
    time_stamp <- as.character.Date(time_stamp)
    datum <- read.csv(data_file)
    rows <- dim(datum)[1]
    time_stamps <- rep(time_stamp,rows)
    
    # alt-name getter func
    get_item <- function(names) {
       for (name in names) {
           if (name %in% colnames(datum)) {
               return(datum[[name]])
           }
       }
       rep(NA,rows)
    }
    
    df <- rbind(df,data.frame(
        date=time_stamps,
        last_update=get_item(last.update),
        lat=get_item(latitude),
        long=get_item(longitude),
        province_state=get_item(province.state),
        country_region=get_item(country.region),
        confirmed=datum[['Confirmed']],
        deaths=datum[['Deaths']],
        recovered=datum[['Recovered']],
        active=rep(NA,rows),
        stringsAsFactors = FALSE
    ))
  }
  df$confirmed[is.na(df$confirmed)] <- 0
  df$deaths[is.na(df$deaths)]       <- 0
  df$recovered[is.na(df$recovered)] <- 0
  df
}
df <- get_dataset()

plt_province_stats <- function(df,is_confirmed=FALSE) {
    time_stamp <- df$date[[length(df$date)]]
    provinces <- c(
        'British Columbia',
        'Manitoba',
        'New Brunswick',
        'Nova Scotia',
        'Ontario',
        'Prince Edward Island',
        'Quebec',
        'Saskatchewan'
    )
    if (!is_confirmed) {
        for (province in provinces) {
            fname <- gsub(" ","_",sprintf("plts/canada/outcomes/K19_%s_Outcomes.png",province))
            png(fname, width=700, height=432)
            print(fname)
            pstats <- df[(df$province_state==province),]
            pstats <- pstats[(pstats$date > "03-12-2020"),]
            plot(as.Date(pstats$date,"%m-%d-%Y"),pstats$confirmed,type='b',xaxs='i',panel.first=grid(),
                 xlab="Days",
                 ylab=paste("Outcomes (Log Scale)"),
                 main=paste(province,"K19 Stats as of",time_stamp),
                 log='y',
                 cex=.7,
                 pch=20
            )
            lines(as.Date(pstats$date,"%m-%d-%Y"),pstats$recovered,col='blue',type='b',cex=.7,pch=20)
            lines(as.Date(pstats$date,"%m-%d-%Y"),pstats$deaths,col='red',type='b',cex=.7,pch=20)
            legend("topleft",
                 legend=c('Confirmed','Recovered','Deaths'),
                 cex=.7,
                 pch=20,
                 col=c('black','blue','red'),
                 lty=1
            )
            dev.off()
        }
    } else {
        for (province in provinces) {
            fname <- gsub(" ","_",sprintf("plts/canada/confirmed/K19_%s_Confirmed.png",province))
            png(fname, width=700, height=432)
            print(fname)
            pstats <- df[(df$province_state==province),]
            pstats <- pstats[(pstats$date > "03-12-2020"),]
            plot(as.Date(pstats$date,"%m-%d-%Y"),pstats$confirmed,type='b',xaxs='i',panel.first=grid(),
                 xlab="Days",
                 ylab=paste("Confirmed"),
                 main=paste(province,"K19 Stats as of",time_stamp),
                 cex=.7,
                 pch=20
            )
            dev.off()
        }
    }
}

plt_prov_stats <- function(df) {
  #provinces <- list('Quebec','Ontario','Manitoba','British Columbia')
  datum <- data.frame(
    province=c('Quebec','Ontario','Nova Scotia','New Brunswick','Saskatchewan','Manitoba','British Columbia','Alberta','Prince Edward Island'),
    color=c("red","blue","pink","gold","orange","black","brown","purple","grey"),
    stringsAsFactors = FALSE
  )
  dates <- unique(df$date)
  zeros <- rep(0,length(dates))
  strs <- rep('',length(dates))
  dc <- data.frame(
    date=character(),
    province=character(),
    confirmed=numeric(),
    deaths=numeric(),
    recovered=numeric(),
    stringsAsFactors = FALSE
  )
  for (date in unique(df$date)) {
    sd <- df[(df$date==date),]
    for (province in datum$province){
      pstat <- sd[(sd$province_state==province),]
      if (dim(pstat)[1] > 0) {
        dc[nrow(dc)+1,] = list(as.character.Date(date),province,pstat$confirmed,pstat$deaths,pstat$recovered)
      } else {
        dc[nrow(dc)+1,] <- list(as.character.Date(date),province,NA,NA,NA)
      }
    }
  }
  dc['recovery'] <- dc$recovered*100.0/dc$confirmed
  dc <- dc[(dc$date > "03-12-2020"),]
  first <- TRUE
  png("plts/canada/K19_Major_Canada_Province_Stats.png", width=700, height=432)
  for (province in datum$province) {
    if (first) {
      plot(
        as.Date(dc[(dc$province==province),]$date,"%m-%d-%Y"),dc[(dc$province==province),]$confirmed,
        xaxs='i',
        ylim=c(min(dc$confirmed,na.rm=TRUE),max(dc$confirmed,na.rm=TRUE)),
        xlab="Days",
        ylab='Confirmed (Log Scale)',
        main=paste('Canada K19 Stats from John Hopkins as of',max(dc$date)),
        type='b',
        cex=.7,
        pch=20,
        col=datum[(datum$province==province),]$color,
        panel.first=grid(),
        log='y'
      )
      first <- FALSE
    } else {
      points(as.Date(dc[(dc$province==province),]$date,"%m-%d-%Y"),dc[(dc$province==province),]$confirmed,type='b',cex=.7,pch=20,col=datum[(datum$province==province),]$color)
    }
  }
  legend("bottomright",
         legend=datum$province,
         cex=.7,
         pch=20,
         col=datum$color,
         lty=1
  )
  dev.off()
}


plt_canada_stats <- function(df) {
  time_stamp <- df$date[[length(df$date)]]
  canada <- df[(df$country_region=='Canada'),]
  # https://stackoverflow.com/questions/1660124/how-to-sum-a-variable-by-group
  png("plts/canada/K19_Canada_Stats.png", width=700, height=432)
  ac <- aggregate(canada$confirmed,by=list(date=canada$date),FUN=sum)
  plot(as.Date(ac$date,"%m-%d-%Y"),ac$x,type='b',xaxs='i',panel.first=grid(),cex=.7,pch=20,col="blue",
       xlab="Days",
       ylab="Confirmed (Log Scale)",
       main=paste("Canada K19 Stats as of",time_stamp),log="y")
  ad <- aggregate(canada$deaths,by=list(date=canada$date),FUN=sum)
  points(as.Date(ad$date,"%m-%d-%Y"),ad$x,type='b',cex=.7,pch=20,col="red")
  legend(
      "topleft",
      legend=c(
          sprintf('Confirmed (%s)',formatC(max(ac$x),format="d",big.mark=",")),
          sprintf('Deaths (%s)',formatC(max(ad$x),format="d",big.mark=","))
      ),
      cex=.7,
      pch=20,
      col=c('blue','red'),
      lty=1
  )
  dev.off()
}

plt_province_stats(df)
plt_province_stats(df,is_confirmed=TRUE)
plt_canada_stats(df)
plt_prov_stats(df)


dw <- data.frame(
  date=unique(df$date),
  confirmed=aggregate(df$confirmed,by=list(date=df$date),FUN=sum)$x,
  deaths=aggregate(df$deaths,by=list(date=df$date),FUN=sum)$x,
  recovered=aggregate(df$recovered,by=list(date=df$date),FUN=sum)$x,
  stringsAsFactors = FALSE
)
dw['recovery_rate'] <- dw$recovered*100.0/dw$confirmed
dw['death_rate'] <- dw$deaths*100.0/dw$confirmed
dw['total_rate'] <- (dw$recovered+dw$deaths)*100.0/dw$confirmed

df_country <- function(Country) {
  dfc <- data.frame(
    date=unique(df[(df$country_region==Country),]$date),
    confirmed=aggregate(df[(df$country_region==Country),]$confirmed,by=list(date=df[(df$country_region==Country),]$date),FUN=sum)$x,
    deaths=aggregate(df[(df$country_region==Country),]$deaths,by=list(date=df[(df$country_region==Country),]$date),FUN=sum)$x,
    recovered=aggregate(df[(df$country_region==Country),]$recovered,by=list(date=df[(df$country_region==Country),]$date),FUN=sum)$x,
    stringsAsFactors = FALSE
  )
  dfc['recovery_rate'] <- dfc$recovered*100 / dfc$confirmed
  dfc
}

get_recovery_rates <- function() {
  countries = c(
    'US','Spain','Italy','France','Germany','China','Iran','UK','Canada','Barbados','Jamaica',
    'Turkey','Switzerland','Belgium','Netherlands','Brazil','Austria','Portugal','South Korea',
    'Israel','Sweden','Australia','Norway','Ireland','India','Chile','Russia','Denmark','Czechia',
    'Poland','Malaysia','Japan','Philippines','Ecuador','Peru','Luxembourg')
  global_recoveries <- c()
  local_recoveries <- c()
  for (country in countries) {
    rc <- df_country(country)
    global_recoveries <- c(global_recoveries,rc$recovery_rate[nrow(rc)]*rc$confirmed[nrow(rc)]/dw$confirmed[nrow(dw)])
    local_recoveries <- c(local_recoveries,rc$recovery_rate[nrow(rc)])
  }
  rr <- data.frame(
    country=countries,
    global_recovery_rate=global_recoveries,
    local_recovery_rate=local_recoveries,
    stringsAsFactors = FALSE
  )
  rr[order(rr$global_recovery_rate,decreasing=TRUE),]
}
recovery_rates <- get_recovery_rates()


rr_str <- c()
chop <- 0.3
reduced_recovery_rates <- recovery_rates[(recovery_rates$global_recovery_rate>chop),]
for (idx in 1:nrow(reduced_recovery_rates)) {
  rr_str <- c(rr_str,sprintf("%s: %.1f%%",reduced_recovery_rates$country[idx],reduced_recovery_rates$global_recovery_rate[idx]))
}
rr_str <- c(rr_str,sprintf("[Global: %.1f%%]",sum(dw$recovery_rate[nrow(dw)])))

rrr_str <- c()
rrr <- recovery_rates[(order(recovery_rates$local_recovery_rate,decreasing = TRUE)),]
rrr <- rrr[(rrr$local_recovery_rate>5),]
for (idx in 1:nrow(rrr)) {
  rrr_str <- c(rrr_str,sprintf("%s: %.1f%%",rrr$country[idx],rrr$local_recovery_rate[idx]))
}
rrr_str <- c(rrr_str,sprintf("[Global: %.1f%%]",sum(dw$recovery_rate[nrow(dw)])))
#for (output in rrr_str) {cat(output,"\n")}

p_order <- 27
x <- seq(length(dw$recovery_rate))
y <- dw$recovery_rate
model <- lm(y ~ poly(x,p_order))
png("plts/K19_World_Outcome_Rates.png", width=700, height=432)
plot(
     as.Date(dw$date,"%m-%d-%Y"),
     dw$death_rate,
     xlab = 'Days',
     ylab='% Outcome Rates',
     ylim=c(0,100),
     main=paste('Global K19 Case Outcome Rates as of',df$date[[length(df$date)]]),
     # https://stackoverflow.com/questions/38594177/changing-date-time-format-in-r
     #main=paste('Global K19 Case Outcome Rates as of',as.POSIXct(as.Date(df$date[[length(df$date)]],"%m-%d-%Y"), format="%m-%d-%Y")),
     type='l',
     xaxs='i',
     yaxs='i',
     col='red',
     panel.first=grid()
)#strptime(as.Date(dw$date,"%m-%d-%Y"), format="%mon %d, %y")
points(as.Date(dw$date,"%m-%d-%Y"),dw$death_rate,cex=.7,pch=20,col='red')
points(as.Date(dw$date,"%m-%d-%Y"),fitted(model),type='l',col='blue')
points(as.Date(dw$date,"%m-%d-%Y"),dw$recovery_rate,cex=.7,pch=20,col='blue')
x <- seq(length(dw$total_rate))
y <- dw$total_rate
model <- lm(y ~ poly(x,p_order))
points(as.Date(dw$date,"%m-%d-%Y"),fitted(model),type='l',col="darkgrey")
minor.tick(nx=0,ny=2,tick.ratio=0.5)
legend("topleft",
       #title="Global Case Outcome Rates",
       legend=c(
           "Recovery_Rate = World_Recovered / World_Confirmed",
           "Death_Rate      = World_Deaths / World_Confirmed",
           "Total_Rate*      = Recovery_Rate + Death_Rate",
           sprintf("World_Confirmed: %s",as.character(comma(dw$confirmed[nrow(dw)],format="d")))
           #"*As the world recovers, the Total_Rate approaches 100%."
       ),
       cex=.7,
       pch=c(20,20,NA,NA),
       col=c("blue","red","darkgrey",NA),
       lty=1
)
dr <- sum(dw$recovery_rate[nrow(dw)])-sum(dw$recovery_rate[nrow(dw)-1])
dra <- if(dr>0) {"\u2191"} else if (dr==0) {"\u2195"} else {"\u2193"}
dd <- sum(dw$death_rate[nrow(dw)])-sum(dw$death_rate[nrow(dw)-1])
dda <- if(dd>0) {"\u2191"} else if (dd==0) {"\u2195"} else {"\u2193"}
dt <- sum(dw$total_rate[nrow(dw)])-sum(dw$total_rate[nrow(dw)-1])
dta <- if(dt>0) {"\u2191"} else if (dt==0) {"\u2195"} else {"\u2193"}
#op <- par(famliy="Courier")
legend("topright",bty='n',
    legend=c(
      sprintf("Recovered: %.2f%% %s %.2f%%",sum(dw$recovery_rate[nrow(dw)]),dra,dr),
      sprintf("Deaths: %.2f%% %s %.2f%%",sum(dw$death_rate[nrow(dw)]),dda,dd),
      sprintf("Total: %.2f%% %s %.2f%%",sum(dw$total_rate[nrow(dw)]),dta,dt)
    ),
    text.col=c("blue","red","darkgrey")
)
#par(op)
#legend("topright",bty='n',title=sprintf("Recovery_Rate Breakdown (>%s%%)",chop),cex=.7,legend=rr_str,text.col="blue")
#text(as.Date(dw$date,"%m-%d-%Y")[1],69.5,
#     paste("Notes: The Total_Rate should approach 100%, as the world recovers.",
#           "These curves should remain fairly unchanged when adjusted for True",
#           "Cases, due to the ratios. They should also remain relatively unchanged",
#           "due to inaccuracies in reporting, due to source variation.",sep="\n"),
#     cex=0.6,pos=4)
remove(x)
remove(y)
dev.off()

#TO-DO: https://plotly.com/r/filled-area-plots/
```


```{r}

states <- c(
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming'
)

#states <- c('Colorado')
#states <- c('New York')
#states <- c('New York City, NY')

accumulate <- function(d,column) {
  cols <- c(d[[column]])
  col <- c(cols[1])
  for (i in 2:length(cols)) {
    col <- c(col,cols[i]+col[i-1])
  }
  d[[column]] <- col
  d
}

plt_state_stats <- function(df,is_confirmed=FALSE) {
    time_stamp <- df$date[[length(df$date)]]
    if (!is_confirmed) {
        for (state in states) {
            fname <- gsub(" ","_",sprintf("plts/us/outcomes/K19_%s_Outcomes.png",state))
            png(fname, width=700, height=432)
            print(fname)
            pstats <- df[(df$province_state==state),]
            #pstats <- pstats[(pstats$date > "03-12-2020"),]
            ac <- aggregate(pstats$confirmed,by=list(date=pstats$date),FUN=sum)
            ar <- aggregate(pstats$recovered,by=list(date=pstats$date),FUN=sum)
            ad <- aggregate(pstats$deaths,by=list(date=pstats$date),FUN=sum)
            plot(as.Date(ac$date,"%m-%d-%Y"),ac$x,type='b',xaxs='i',panel.first=grid(),
                 xlab="Days",
                 ylab=paste("Outcomes (Log Scale)"),
                 main=paste(state,"K19 Stats as of",time_stamp),
                 log='y',
                 cex=.7,
                 pch=20
            )
            lines(as.Date(ad$date,"%m-%d-%Y"),ad$x,col='red',type='b',cex=.7,pch=20)
            # TO-DO: Fix recoved problem...
            if (max(ar$x)>0) {
                lines(as.Date(ar$date,"%m-%d-%Y"),ar$x,col='blue',type='b',cex=.7,pch=20)
                 legend("bottomright",
                     legend=c(
                       sprintf('Confirmed (%s)',formatC(max(ac$x),format="d",big.mark=",")),
                       sprintf('Recovered (%s)',formatC(max(ar$x),format="d",big.mark=",")),
                       sprintf('Deaths (%s)',formatC(max(ad$x),format="d",big.mark=","))
                     ),
                     cex=.7,
                     pch=20,
                     col=c(
                       'black',
                       'blue',
                       'red'),
                     lty=1
                )
            } else {
                legend("bottomright",
                     legend=c(
                       sprintf('Confirmed (%s)',formatC(max(ac$x),format="d",big.mark=",")),
                       sprintf('Deaths (%s)',formatC(max(ad$x),format="d",big.mark=","))
                     ),
                     cex=.7,
                     pch=20,
                     col=c(
                       'black',
                       'red'),
                     lty=1
                )
            }
            dev.off()
        }
    } else {
        for (state in states) {
            fname <- gsub(" ","_",sprintf("plts/us/confirmed/K19_%s_Confirmed.png",state))
            png(fname, width=700, height=432)
            print(fname)
            pstats <- df[(df$province_state==state),]
            #pstats <- pstats[(pstats$date >= "04-12-2020"),] # TO-DO: Not working???
            #pstats <- pstats[(pstats$date > "03-12-2020"),]
            #pstats <- df[(df$province_state==state),] # duplicate -- remove
            ac <- aggregate(pstats$confirmed,by=list(date=pstats$date),FUN=sum)
            plot(as.Date(ac$date,"%m-%d-%Y"),ac$x,type='b',xaxs='i',panel.first=grid(),
                 xlab="Days",
                 ylab=paste("Confirmed"),
                 main=paste(state,"K19 Stats as of",time_stamp),
                 cex=.7,
                 #log='y',
                 pch=20
            )
            legend("topleft",
                 legend=sprintf('Confirmed (%s)',formatC(max(ac$x),format="d",big.mark=",")),
                 cex=.7,
                 pch=20,
                 col='black',
                 lty=1
            )
            dev.off()
        }
    }
}

plt_us_stats <- function(df) {
  time_stamp <- df$date[[length(df$date)]]
  us <- df[(df$province_state %in% states),]
  png("plts/us/K19_US_Stats.png", width=700, height=432)
  ac <- aggregate(us$confirmed,by=list(date=us$date),FUN=sum)
  plot(as.Date(ac$date,"%m-%d-%Y"),ac$x,type='b',xaxs='i',panel.first=grid(),cex=.7,pch=20,col="blue",
       xlab="Days",
       ylab="Confirmed (Log Scale)",
       main=paste("US K19 Stats as of",time_stamp),log="y")
  ad <- aggregate(us$deaths,by=list(date=us$date),FUN=sum)
  points(as.Date(ad$date,"%m-%d-%Y"),ad$x,type='b',cex=.7,pch=20,col="red")
  legend(
      "topleft",
      legend=c(
          sprintf('Confirmed (%s)',formatC(max(ac$x),format="d",big.mark=",")),
          sprintf('Deaths (%s)',formatC(max(ad$x),format="d",big.mark=","))
      ),
      cex=.7,
      pch=20,
      col=c('blue','red'),
      lty=1
  )
  dev.off()
}

plt_us_stats(df)

plt_state_stats(df,is_confirmed=TRUE)
plt_state_stats(df,is_confirmed=FALSE)
```

```{r}

plt_multi_province_stats <- function(df) {
    time_stamp <- df$date[[length(df$date)]]
    provinces <- c(
        'British Columbia',
        'Manitoba',
        'New Brunswick',
        'Nova Scotia',
        'Ontario',
        'Prince Edward Island',
        'Quebec',
        'Saskatchewan'
    )
    mfrow.old <- par()$mfrow
    mar.old <- btm_mars <- top_mars <- par()$mar
    btm_mars[1] <- top_mars[3] <- 0.25
    btm_mars[2] <- top_mars[2] <- 7.1
    scipen <- options()$scipen
    options(scipen=999)
    for (province in provinces) {
        pstats <- df[(df$province_state==province),]
        pstats <- pstats[(pstats$date > "03-12-2020"),]
        fname <- gsub(" ","_",sprintf("plts/canada/multi/K19_%s_Outcome_Linear_Plots.png",province))
        png(fname, width=700, height=432)
        print(fname)
        par(mfrow=c(2,1))
        par(mar=btm_mars)
        plot(as.Date(pstats$date,"%m-%d-%Y"),pstats$confirmed,type='b',xaxs='i',panel.first=grid(),
            xlab="",
            xaxt='n',
            ylab="",
            yaxt='n',
            main=paste(province,"K19 Stats as of",time_stamp),
            cex=.7,
            pch=20
        )
        mtext(side=2,"Confirmed",line=4.)
        axis(2,las=1)
        par(mar=top_mars)
        plot(as.Date(pstats$date,"%m-%d-%Y"),pstats$deaths,type='b',xaxs='i',panel.first=grid(),
            xlab="Days",
            ylab="",
            yaxt='n',
            cex=.7,
            pch=20,
            col='red'
        )
        mtext(side=2,"Deaths",line=4.)
        axis(2,las=1)
        dev.off()
    }
    par(mfrow=mfrow.old,mar=mar.old)
    options(scipen=scipen)
}


plt_multi_province_stats(df)



```

```{r}

plt_multi_state_stats <- function(df) {
    time_stamp <- df$date[[length(df$date)]]
    mfrow.old <- par()$mfrow
    mar.old <- btm_mars <- top_mars <- par()$mar
    btm_mars[1] <- top_mars[3] <- 0.25
    btm_mars[2] <- top_mars[2] <- 7.1
    scipen <- options()$scipen
    options(scipen=999)
    for (state in states) {
        pstats <- df[(df$province_state==state),]
        ac <- aggregate(pstats$confirmed,by=list(date=pstats$date),FUN=sum)
        ad <- aggregate(pstats$deaths,by=list(date=pstats$date),FUN=sum)
        fname <- gsub(" ","_",sprintf("plts/us/multi/K19_%s_Outcome_Linear_Plots.png",state))
        png(fname, width=700, height=432)
        print(fname)
        par(mfrow=c(2,1))
        par(mar=btm_mars)
        plot(as.Date(ac$date,"%m-%d-%Y"),ac$x,type='b',xaxs='i',panel.first=grid(),
            xlab="",
            xaxt='n',
            ylab="",
            yaxt='n',
            main=paste(state,"K19 Stats as of",time_stamp),
            cex=.7,
            pch=20
        )
        mtext(side=2,"Confirmed",line=4.)
        axis(2,las=1)
        par(mar=top_mars)
        plot(as.Date(ad$date,"%m-%d-%Y"),ad$x,type='b',xaxs='i',panel.first=grid(),
            xlab="Days",
            ylab="",
            yaxt='n',
            cex=.7,
            pch=20,
            col='red'
        )
        mtext(side=2,"Deaths",line=4.)
        axis(2,las=1)
        dev.off()
        }
}

plt_multi_state_stats(df)

```





